### ISSUE TITLE
Support absolute path for image link

### ISSUE THREAD

**Issue by johnking** [neilsustc/vscode-markdown#118]
## Problems
I need to use **absolute path** for images in order to display the images correct in my application. 

It seems that `vscode-markdown` does not support absolute path for  image link now

## How to reproduce? 

change the relative path to absolute path. 

![image alternative text](relative/path/to/image file),  *it works*

![image alternative text](absolute/path/to/image file),  it *does not work*

**Comment by neilsustc** [comment]
I think it is a bug of vscode v1.21.0 (because this extension do nothing about your images 😂).
And it is not only the image path but also paths of stylesheets, etc. go wrong.

Related [vscode#45155](https://github.com/Microsoft/vscode/issues/45155), [vscode#45007](https://github.com/Microsoft/vscode/issues/45007)

**Comment by johnking** [comment]
Hi Yu, 

  thanks for your quick reply, I am using `vscode` version 1.20.1

  let me try other tools to see what's wrong here. 

thanks

**Comment by neilsustc** [comment]
> We now restrict the markdown preview to only loading resources inside the current workspace for security reasons
> <https://github.com/Microsoft/vscode/issues/45260#issuecomment-371428889>

This is the decision by vscode team. I afraid I cannot do much on my side.

**Comment by tifDev** [comment]
Lol [link](https://github.com/microsoft/vscode/issues/45260#issuecomment-371428889) Lol, this works on windows why they are blocking this in linux
