### ISSUE TITLE
1. outline; 2. toc; 3. &emsp;

### ISSUE THREAD

**Issue by SPA-SPA-SPA** [neilsustc/vscode-markdown#175]
# normal 0. it work.
![normal](https://user-images.githubusercontent.com/22609128/39814590-8a4f02ba-53c7-11e8-9644-8a106ab95446.gif)
# problem 1. outline updates when you save file instead of updating the toc.
![bug1](https://user-images.githubusercontent.com/22609128/39814825-6b102ae0-53c8-11e8-8fe4-10fcdb04014f.gif)
# problem 2.1 when there is Chinese in the first header, toc can not be updated.
![bug2_1](https://user-images.githubusercontent.com/22609128/39815230-ec41d00e-53c9-11e8-8aa8-59573f5db95c.gif)
# problem 2.2 when there is change in the first header, toc can not be updated.
![bug2_2](https://user-images.githubusercontent.com/22609128/39815284-14b83460-53ca-11e8-9831-24fab556d827.gif)
# problem 3. something like `&emsp;` can be seen in the outline, which doesn't look good. 
![bug3](https://user-images.githubusercontent.com/22609128/39815450-910f5dcc-53ca-11e8-8d36-bf395a7d54ff.gif)
**that's all i found. hope you guys can fix it, thank you!**

**Comment by neilsustc** [comment]
One tip in the beginning, the option `toc.updateOnSave` is `true` by default. So you don't need to execute `utoc` manually.

For problem 1, it is by design. Of course we can even update outline as you type every character. But it is not necessary, right? And since we can also update TOC on file save, you only need to press <kbd>Ctrl</kbd> + <kbd>S</kbd> and everything is updated.

Problem 2.1 and 2.2. They are already reported in #48. We need a smarter rule to detect the TOC.

Problem 3. This is a new issue. I will fix it soon.

**Comment by neilsustc** [comment]
Another known issue is Chinese characters will be removed in the generated link anchors ([vscode#48482](https://github.com/Microsoft/vscode/issues/48482)).

A workaround is setting `toc.githubCompatibility` to `true`.

**Comment by neilsustc** [comment]
Preview build `v1.3.0-fix171-175` is available [here](https://github.com/neilsustc/vscode-markdown/releases/)
