### ISSUE TITLE
Markdown links are expected in small letters, but vscode accepts it in capital letters.

### ISSUE THREAD

**Issue by chuacw** [neilsustc/vscode-markdown#183]
Markdown links are expected in small letters, but vscode-markdown accepts capital letters.

Create a header, and then create a link to it.
For example, as header:
The first link below works in vscode-markdown, but when you move it to Github markdown, it doesn't work.

The second link below works in both vscode-markdown and Github markdown.
- [Example configurations - doesn't work](#Example-configurations)
- [Example configurations - works](#example-configurations)

Link here

Example configurations
==============

No

**Comment by neilsustc** [comment]
This extension does nothing about it.
You might need to open an issue in Microsoft/vscode repository.

**Comment by mlafleur** [comment]
I've been looking for this as well. Just to clarify, this refers to the URI [Fragment Identifier](https://tools.ietf.org/html/rfc3986#section-3.5) for each header. The header `id` get generated as lower-cased with each space replaced by `-` and other symbols dropped.  Since URL fragments are often case-sensitive (the spec is frustratingly silent on fragments and case-sensitivity), links to them should always be lower-cased to ensure they work everywhere. 

It would be nice if the extension supported optionally auto-correcting URI fragments to lower-case.

**Comment by neilsustc** [comment]
Close since we can do nothing about it
