### ISSUE TITLE
Emphasis not working on words with non-alphanumeric first character

### ISSUE THREAD

**Issue by onomori** [neilsustc/vscode-markdown#184]
**What is the problem?**
1. Bold and Italic don't work when the first character of the word to be emphasized is a non-letter or non-number character. The preview renders it corrently, though.

**How can I reproduce it?**
1. Try to bold or italize `**(Lorem Ipsum)**` or `**.config**`. The color doesn't change.

Related note but maybe not, really: When you try the same thing above but on a part of a word, it doesn't work either and doesn't get rendered corrently. 

For example when you try to bold the "@gmail.com" part of `example**@gmail.com**`, likeso, or `vscode**-markdown**` it doesn't work either and the preview doesn't render it properly either. I just checked though and looks like Github Markdown doesn't support this either but I don't know if that's a bug or not. It looks like a pretty edge case though so I'm not sure if it's worth the time.

**Comment by neilsustc** [comment]
That is because your words start or end with punctuations. According to the [CommonMark Spec](https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis), they are not parsed as emphasis blocks. Those characters are

![image](https://user-images.githubusercontent.com/7588612/40463622-db021076-5f48-11e8-9bc2-88e5aa34b867.png)

**Comment by onomori** [comment]
Ah, it is there. Got it, I'll just work around the emphasis  in my file. Thanks for the explanation!
