### ISSUE TITLE
Color of ticked tasks is hard to see

### ISSUE THREAD

**Issue by Splike** [neilsustc/vscode-markdown#192]
The check-mark color of completed tasks is too close the the actual color of the check-mark box. Is it possible to tweak the check-mark color, so there is more contrast and therefore easier to see when something is checked off?

**Comment by neilsustc** [comment]
The checkbox control is implemented by the browser. And it will be rendered differently in different browsers. I am afraid that we cannot change its style easily.

VSCode (-> Electron -> Chromium)

![image](https://user-images.githubusercontent.com/7588612/40776171-8e3344d6-64fc-11e8-9058-0c6f11cb6d97.png)

Microsoft Edge

![image](https://user-images.githubusercontent.com/7588612/40776185-9ae30eaa-64fc-11e8-9f27-24f4b73c2d5c.png)

**Comment by Splike** [comment]
Oh, that's a shame. The faded out grey colors simply don't work very will :(

**Comment by JamesO2x** [comment]
Hi, I know this issue is marked as closed, but I'm having the exact same issue.

There's another extension that just creates colored checkboxes in MarkDown preview, but it unfortunately causes conflict with this extension.

I made a post about it there, and I actually thought I was having issue with that person's extension when it was actually this one. You can see the thread here: https://github.com/mjbvz/vscode-markdown-checkboxes/issues/13

If you install that extension, it will turn completed Checkboxes blue (but only if you disable _**this**_ extension first). So having the checkboxes colored is definitely possible.

**Comment by Lemmingh** [comment]
Matt Bierner's `bierner.markdown-checkbox` renders checkboxes as "enabled `<input>` elements", while ours produces "disabled elements".

As mentioned above, it's the web browser (Chromium) that decides how to present the enabled-disabled state. **We CANNOT control it.**

**Comment by JamesO2x** [comment]
Ah, that makes sense. How can I modify the extension to render Enabled input elements instead then? That seems like a pretty straightforward solution.

**Comment by yzhang-gh** [comment]
There was a PR #962 but didn't get merged.

As a workaround, you can open `~/.vscode/extensions/yzhang.markdown-all-in-one-xxx/dist/extension.js` and change

```
e.use(n(11))
```
to
```
e.use(n(11), {enabled: true})
```

Reload VS Code and the checkboxes will be enabled.

**Comment by JamesO2x** [comment]
Thank you so much! This is exactly what I was looking for.
