### ISSUE TITLE
Extension Does Nothing

### ISSUE THREAD

**Issue by gpresland** [neilsustc/vscode-markdown#22]
Windows 10, x64.
Visual Studio Code ver 1.14.1.
Shell 1.6.6.
Renderer 56.0.2924.87.
Node 7.4.0.
Markdown All in One - Yu Zhang v0.7.5.

Computer it is running on is 7 days old and all software is freshly installed.

Installing the extension for the first time followed by a reload of VS Code, then editing a Markdown (`.md`) file caused VS Code to spam keyboard input hook errors on the top address bar (cannot recall exact error messages). After uninstall and reinstalling followed by another VS Code reload, the keyboard hook errors have gone away but the extension has no effect on Markdown (`.md`) files. It is as if the extension is disabled yet it is not.

**Comment by neilsustc** [comment]
Thanks for your feedback. It is a [known issue](https://github.com/neilsustc/vscode-markdown/issues/14) if you only open a single Markdown file.

It is a critical bug and I will resolve it soon.

**Comment by neilsustc** [comment]
Please try v0.7.6

**Comment by gpresland** [comment]
> Please try v0.7.6

Same issue; VS Code handles `md` files as if the extension wasn't installed.

**Comment by neilsustc** [comment]
That's really strange 🤔.

Could you please describe how you open a `md` file? For example, do you

- With no vscode instance running, right click `md` file and select "open with vscode"? Or
- Use "open file" with existing vscode instance?

If possible, can you upload your `md` file (or a sample file for test).

**Comment by neilsustc** [comment]
Okay, finally I decide to go back to legacy activation events. There should be no problem now.

**Comment by rbolsius** [comment]
I was also going to suggest just switching to a simple "onLanguage:markdown" activation event.  It seems like this is the best event to use to activate the extension since it doesn't perform any expensive file scans over the project and it is possible to enable the extension even when creating a new markdown file that has not been saved yet.  Another benefit is that the extension will be activated regardless what extension the user chooses for the markdown files.

**Comment by neilsustc** [comment]
@rbolsius Thanks a lot for your suggestions! You are really nice ❤

> ...  just switching to a simple "onLanguage:markdown" activation event ... it is possible to enable the extension even when creating a new markdown file that has not been saved yet.

Yes. Totally agree. And that's why I finally gave up writing my own activation events 😅.

> I'm not sure if the"workspaceContains:README.md"event is necessary

From the perspective of usage, I think it's not necessary.
But there is a (slightly?) noticeable delay when user open a Markdown file for the first time.
I use `README.md` because I would like to provide the best experience.
And adding an additional `README.md` won't hurt the performance because it only scans the depth 1 (but `*.md` will #12). So I think `README.md` is a icing on the cake. What is your opinion?

**Comment by rbolsius** [comment]
Yeah, that sounds good to me also since it will just look for README.md in the root folder.  I tried it with my large project and workspaceContains:README.md performs well unlike the previous *.md event.

**Comment by neilsustc** [comment]
@gpresland Hope you like this solution.

**Comment by gpresland** [comment]
Appears to be working now 👍

**Comment by JackHowa** [comment]
This seems to be a problem for me. I'm not using README.md. Looking for the onLanguage:markdown activation setting.

**Comment by neilsustc** [comment]
@JackHowa `onLanguage:markdown` is already one of the activation events. See <https://github.com/neilsustc/vscode-markdown/blob/master/package.json#L26-L29>

So there might be some other reasons if you find it not working. Could you please navigate to "menubar>help>toggle developer tools" and see whether there are something related.
