### ISSUE TITLE
TOC create and update not working

### ISSUE THREAD

**Issue by peterschussheim** [neilsustc/vscode-markdown#275]
#### What is the problem?

Creating or updating existing TOC blocks in markdown files doesn't work.  Upon executing the command, nothing happens.

#### Is there any error message in the console?

no messages in devtools

**Comment by neilsustc** [comment]
All TOC functionalities are broken in the latest vscode insider build... That's caused by the internal changes of the vscode built-in markdown extension. I need to think about removing the dependency on it...

**Comment by peterschussheim** [comment]
Is there any chance of creating an independent extension, with just TOC functionality?  I have tried other extensions however, yours has the best TOC features by far.

**Comment by neilsustc** [comment]
There are two things
1. Dependency on the vscode built-in extension. It's relatively a big change, and will take some time given that I don't have enough time now.
2. Only the TOC features. This is easy but I guess it is not necessary...

---

For now, I would suggest opting out from the vscode insider channel so that the TOC features can work well.

**Comment by texastoland** [comment]
Interesting Microsoft/vscode@281f242cfff7231515eeb3ef195bb237ae3182db added `githubSlugifier`. Nothing [in the history](https://github.com/Microsoft/vscode/commits/49edd3d0384e8196fc45bf1a465a434a84ed430e/extensions/markdown-language-features/src/tableOfContentsProvider.ts) was removed just refactored right? Would it make sense to separate `TocProvider` that switches APIs and throws errors next time the data shape changes?

**Comment by neilsustc** [comment]
This should be fixed with the [development build](https://ci.appveyor.com/project/neilsustc/vscode-markdown/build/artifacts).

**Comment by texastoland** [comment]
Working!

**Comment by texastoland** [comment]
Broke again.

```
Activating extension 'yzhang.markdown-all-in-one' failed: Cannot find module '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/out/tableOfContentsProvider'.
```

**Comment by neilsustc** [comment]
After taking a look at the latest build of vscode, I find we can no longer "import"/reuse vscode's codes, **completely**.

A good thing is that I realise this dependency is not necessary anymore. (We no longer need to contribute to outline view (TOC) since vscode takes it over.)

I can even expect a better performance by removing this dependency. The only problem is I might not have time in the near future. If someone is interested, here is the only method we need to implement by ourselves

https://github.com/neilsustc/vscode-markdown/blob/1c1272202c115c29a27fc1d637aa5eb67e97fa3d/src/toc.ts#L230

**Comment by neilsustc** [comment]
I changed my mind. It breaks the whole extension 😂.

Fixed with v1.6.2.

**Comment by texastoland** [comment]
Verified!

**Comment by mprasil** [comment]
I get following message when trying to create / update TOC in v1.6.2 and VS Code 1.28.0:
```
Cannot read property '1' of null
```

**Comment by neilsustc** [comment]
@mprasil Could you please provide more context (e.g. your Markdown content, more detailed error message)? No one can reproduce a problem with just the error message...

**Comment by mprasil** [comment]
Apologies for missing the details, I was in a bit of a hurry and wanted to get to this issue next day. To be specific, I was working on [this specific file](https://raw.githubusercontent.com/mprasil/dronelab/d2748892670cac118fbf2dd1ce4b0cc5deabab3d/Readme.md). You just need to remove the TOC there as that was later added by another TOC plugin.

It appears that the functionality broke as I updated to latest VS Code release.

As for the error message, unfortunately this popup is the only thing I can see:

![image](https://user-images.githubusercontent.com/8255364/46725492-35760600-cc74-11e8-812d-4ee8308a15d2.png)

There's no message in the debug console or anywhere else. I'm not familiar with debugging VS Code plugins, so if there's something I can do to get some more info, let me know.

**Comment by neilsustc** [comment]
@mprasil Many thanks! I can reproduce now. The problem is the `#.drone.yml` in the code block is wrongly treated to be a heading.

And it is fixed now. Download the dev build [here](https://ci.appveyor.com/project/neilsustc/vscode-markdown/build/artifacts).

**Comment by mprasil** [comment]
I can verify that the fixed version works fine. Thanks!

**Comment by peterschussheim** [comment]
closing this, original problem reported fixed.  Thank you @neilsustc 👍
