### ISSUE TITLE
"Print document to HTML" encodes `\` in image paths to `%5C`

### ISSUE THREAD

**Issue by JeffRockatansky** [neilsustc/vscode-markdown#282]
#### What is the problem?
- When printing to HTML, relative path from markdown `![](\assets\03_05.PNG "")` turns into this `<img src="file:///e%3A/fakepath/%255Cassets%255C03_05.PNG" alt="">` in HTML, and Chrome could not use it to add image on page. 
#### How can I reproduce it?
1. F1 > Markdown: Print current document to HTML
2. Open HTML in Chrome Cannary or Chrome
#### Is there any error message in the console?
No errors in dev tools.

**Comment by neilsustc** [comment]
I recommend using `/` rather than `\` since `\` will be encoded to URL by the Markdown render

![image](https://user-images.githubusercontent.com/7588612/45973462-7ba55580-c036-11e8-8467-e17f4ed39df7.png)

VSCode does a little more to normalize the image path so it works well.

And for using relative/absolute path, you can change the option `print.absoluteImgPath` as your preference.
