### ISSUE TITLE
Slow to edit large markdown file

### ISSUE THREAD

**Issue by kenng** [neilsustc/vscode-markdown#323]
#### What is the problem?
Slow to edit large markdown file when the plugin is active.  If optimisation is difficult, probably offer an option to toggle on/off it for large file. As the plugin is really useful to generate the table of content. 

#### How can I reproduce it?
You can use this file to test 
https://gist.github.com/kenng/b04e246ee269ebd2e38b102047d1b1ec

#### Is there any error message in the console?
No error.

**Comment by neilsustc** [comment]
I can confirm

**Comment by muuvmuuv** [comment]
Something like that would help to just render the viewed content: https://twitter.com/ChromiumDev/status/1062433100804702208

**Comment by josephzjw** [comment]
me too, after disable this extension it is faster...

**Comment by michaelbarkdoll** [comment]
I'm also experiencing this issue.

**Comment by neilsustc** [comment]
Will investigate it when I come back from the holiday

**Comment by neilsustc** [comment]
That will be great!

And I would suggest uninstalling this extension before debugging this issue. The extension overwriting might cause some confusion. (see [here](https://github.com/Microsoft/vscode/issues/50254#issuecomment-392518499))

**Comment by upupming** [comment]
For problem 2, I have tested many times, here is the solution:

1. The code you wrote is fast, just takes at most 30ms to finish.
2. When our callback function such as `onEnterKey` has an edit on the markdown file using `commands.executeCommand('type'...` etc, the code runs fast too.
3. However, when we call the handler `onEnterKey` twice continuously, the second call has to wait for about 5~6s ~before the first call finishes~, don't know why. When the second call gets stuck, I can see VS Code is using almost 1.5GB memory.
4. If I don't edit the file, i.e. comment all code like `commands.executeCommand('type'...`, two continuous call of the handler is fast again.

So there must be something wrong on `commands.executeCommand('type'`(by the way, I cannot see find any documentation about this `type` command). 

I have also tried using [`TextEditorEdit.insert`](https://code.visualstudio.com/api/references/vscode-api#TextEditorEdit) to insert contents, but continuously call of `onEnterKey` will get the following warning:

```txt
Edits from command markdown.extension.onEnterKey were not applied.
extensionHostProcess.js:715
Edits from command markdown.extension.onEnterKey were not applied.
extensionHostProcess.js:715
Edits from command markdown.extension.onEnterKey were not applied.
extensionHostProcess.js:715
Edits from command markdown.extension.onEnterKey were not applied.
extensionHostProcess.js:715
Edits from command markdown.extension.onEnterKey were not applied.
```

I'm trying to find another vs code extension which handles this problem gracefully.

**Comment by upupming** [comment]
Probably this is a problem with vs code's extension API, I'm not quite sure now.

**Comment by upupming** [comment]
Okay, I found the problem is not on the side of vs code itself.

After some profile following the [performance guide](https://github.com/Microsoft/vscode/wiki/Performance-Issues), I find the most cost function is `editDistance`, which takes 84.34% of the total time.

![image](https://user-images.githubusercontent.com/24741764/51265767-73fa2a00-19f4-11e9-81bc-459cd5fd0408.png)

If I comment this line: https://github.com/neilsustc/vscode-markdown/blob/08da4d53aac689531f3fc3dc3224fb3f5aeb2e2d/src/extension.ts#L34
the editing of large markdown files will be very fast!

Some analysis of the `editDistance`: https://github.com/neilsustc/vscode-markdown/blob/08da4d53aac689531f3fc3dc3224fb3f5aeb2e2d/src/toc.ts#L156-L182

It takes **O(n^2)** time, which is too, slow, so we should use dynamic programming to make it faster. Need further investigating!

**Comment by neilsustc** [comment]
😅 Thanks anyway.

I tried to disable some of the features (e.g. TOC) to find out a smallest extension that still has this issue. That was the Microsoft/vscode#50254.

Now I am curious about whether this issue is still there if we comment out all other features except for 
`listEditing.activate(context);` here

https://github.com/neilsustc/vscode-markdown/blob/08da4d53aac689531f3fc3dc3224fb3f5aeb2e2d/src/extension.ts#L29-L51

If so, I think we can continue on this train of thought to find the smallest extension sample. (The one in Microsoft/vscode#50254 is small but is not issue-reproducible...)

**Comment by neilsustc** [comment]
> Some analysis of the `editDistance`: 
> It takes **O(n^2)** time, which is too slow, so we should use dynamic programming to make it faster. Need further investigating!

Or a better heuristics for TOC detection.

**Comment by upupming** [comment]
Another question, you generated a new TOC in `detectTocRange` to compare with all lists, but don't update it, it may be time-consuming. 

Can we just simplify the TOC detection by adding something like this:

```html
<!-- begin table of content(Markdown All in One) -->
...
<!-- end table of content(Markdown All in One) -->
```

**Comment by upupming** [comment]
The calculation of Levenshtein_distance [cannot be faster than O(n^2 - ε) for any ε greater than zero](https://en.wikipedia.org/wiki/Levenshtein_distance#Computational_Complexity). We must use another approach for TOC detection.

**Comment by quicktrick** [comment]
I encountered this issue too.  Too slow work with large markdown files (5000 lines and more).  I have to disable this extension to work normally.  It's very inconvenient, because I use this extension extensively. Is it possible to disable some features in settings that slow down editing?  I don't use toc, I've disabled `toc.updateOnSave`, but it does not help.

**Comment by yzhang-gh** [comment]
Could you profile this extension as described [here](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions)? Then we will know the reason.

**Comment by yzhang-gh** [comment]
Tracked in a separate issue.

---

For the people who have also experienced the performance issue, feel free to open a new one (with the CPU profile).
