### ISSUE TITLE
[Feature Request] Use inherited numbering for TOC numbering

### ISSUE THREAD

**Issue by mattogrady87** [neilsustc/vscode-markdown#336]
What I mean is, if I have these headings:
```
# Top level
## First  top level
## Second  below top level

# New Top Level
## First below "New Top Level"
## Second below "New Top Level"
```

It'd be cool if we could number them like this:

1. Top Level
     1.1 First Top Level
     1.2 Second Top Level

2. New Top Level
    2.1 First below new top Level
    2.2 Second below new top level

Rather than always starting at 1. as is the only feature I can find in the current build.

Thank you!

**Comment by neilsustc** [comment]
It is possible but then the problem is they are no longer lists since Markdown doesn't allow list like `1.1`

```markdown
1. one
   1. another one
2. two
```

1. one
   1. another one
2. two

On selection

![image](https://user-images.githubusercontent.com/7588612/49310408-1bb7a900-f4d6-11e8-9b4f-5f6969dca2df.png)

```markdown
1. one
   1.1 another one
2. two
```

1. one
   1.1 another one
2. two

On selection

![image](https://user-images.githubusercontent.com/7588612/49310455-44d83980-f4d6-11e8-8e55-a92a70e9a483.png)

**Comment by mattogrady87** [comment]
I didn't even realize it needed to be a proper list.  I was just used to using "Markdown TOC" by AlanWalk and the numbering is made that way by default.

I think the difference is that his add-on numbers the actual headings in your document and then the TOC is build based off that.

My workaround currently is to just use his for the numbering then yours for the actual TOC build, as his TOC builder has broken for me recently.

Thanks for the reply and the awesome add-on!
