### ISSUE TITLE
Add a "Toggle side preview" command ?

### ISSUE THREAD

**Issue by dorian-marchal** [neilsustc/vscode-markdown#86]
Is it possible to add a "Toggle side preview" command ? It would open/close the preview of the currently focused markdown file.

This is the way `markdown-preview` package works on Atom, with its `markdown-preview:toggle` command (bound on <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>M</kbd> by default).

**Comment by neilsustc** [comment]
This is implemented by the official MD extension (right top corner)

![image](https://user-images.githubusercontent.com/7588612/35860461-16c6554a-0b7f-11e8-93dc-0abddd11034c.png)

**Comment by dorian-marchal** [comment]
This is an "__open__ side preview", not "toggle".
It opens the side preview but does not closes it when it's already opened.

**Comment by neilsustc** [comment]
I'm afraid it cannot be implemented given current vscode APIs.
To my knowledge, we cannot get some editor by name or id etc.

**Comment by robertpeteuil** [comment]
I would love this feature also.

I just discovered your extension and its great support of markdown.  Unfortunately, I just discovered the lack a hotkey to toggle a preview.  Is the only option running the command "Markdown: Open Preview"?

This ia bummer for me, as I'm switching from another extension [preview-vscode](https://github.com/searKing/preview-vscode) which does have the ability to "toggle" previews of Markdown, rst, HTML, and more.  

It's previews for Markdown leave a lot to be desired, which is why I'm trying to switch to your extension. Perhaps you can investigate how they use the API to achieve this.

**Comment by neilsustc** [comment]
Please try [this beta version](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.1.0-fix86.vsix).
