### ISSUE TITLE
Respect indentation rules when pressing Enter

### ISSUE THREAD

**Issue by neilsustc** [neilsustc/vscode-markdown#9]
To make editing list easier, this extension overrides the <kbd>Enter</kbd> key behavior (by adding a <kbd>Enter</kbd> keyboard shortcut which will call `onEnterKey`).
But the <kbd>Enter</kbd> key behavior is not fully re-implemented (the indentation rules). Maybe I should investigate how vscode deals with the <kbd>Enter</kbd> key.

**Comment by neilsustc** [comment]
### Basic

- preserve previous line's indentation
- indent on `(`, `[` and `{`
- outdent on `)`, `]` and `}`

These seem to be enough for many languages which use `{`

### Advanced

language-aware indentation rules (e.g. `:` in Python)

Better to figure out how to embedd language clients like JS and CSS sections in HTML

**Comment by axefrog** [comment]
Thanks! I'll give it a go and let you know how it feels to use.

**Comment by axefrog** [comment]
![vsmarkdown-autoformatting](https://user-images.githubusercontent.com/298883/27843440-c2d03320-6156-11e7-8966-833d91a21cd8.gif)

Auto-formatting is still off. I can live with it, but as you continue to develop and improve the extension over time, it might be worth thinking about the underlying approach you're taking. Rather than trying to reimplement a subset of expected existing behaviour, maybe there's a better way that gives you the best of both worlds? There are many ways to skin a cat. Sometimes there is a better way that you haven't thought of yet.

**Comment by neilsustc** [comment]
I've opened an [issue](https://github.com/Microsoft/vscode/issues/30108) in vscode repo to request a solution for this. Let's wait and see.

**Comment by neilsustc** [comment]
Please checkout v0.8.3
