### ISSUE TITLE
Non-latin TOC does not work on github

### ISSUE THREAD

**Issue by Amomum** [neilsustc/vscode-markdown#90]
Links in the generated table of contents do not work on github but do work in preview.

This is an example of a header and generated TOC:

```
- [Краткое содержание курса](#%D0%BA%D1%80%D0%B0%D1%82%D0%BA%D0%BE%D0%B5-%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D1%83%D1%80%D1%81%D0%B0)

# Краткое содержание курса

```

No, since the error doesn't appear locally.

I saw several issues related to non-latin TOC (#11, #34) but unfortunately they were written in chinese and I couldn't understand why they were closed.

**Comment by neilsustc** [comment]
The non-latin characters are escapsed when encoding into URL, so you see many `%D0` etc.

It works in vscode because the preview is generated exactly in this way.

I then tested the generated HTML in different browsers, finding that it is the problem of browser.
Micosoft Edge ✘
Google Chrome ✓

So I would suggest using other browsers which support this kind of anchors.

**Comment by Amomum** [comment]
Hmm. Generated HTML does indeed work in Chrome but the problem is not in generated HTML.
I pushed a repo with README.md to github and there TOC doesn't work even in Chrome.

Similar links with escaped encoding from wikipedia are working.

**Comment by neilsustc** [comment]
Could you provide some sample codes? I just tested some Chinese characters and the toc link works well.

**Comment by Amomum** [comment]
I created a repo with a sample readme.md file - https://github.com/Amomum/test_TOC
I tried it in firefox and chrome and latin-only links in the TOC work while cyrillic do not.

**Comment by neilsustc** [comment]
I will introduce an option `encodeUrl` later

**Comment by Amomum** [comment]
Thank you :)

**Comment by neilsustc** [comment]
Please try v1.1.0

**Comment by Amomum** [comment]
Something broke really good in v1.1.0; now I can't do anything - hitting `Enter` gives me a warning `command markdown.extension.onEnterKey not found`. Hitting backspace gives a similar warning.
Creating TOC gives an error `command markdown.extension.toc.create not found`.

I tried installing and reinstalling several times with no success.

**Comment by neilsustc** [comment]
You need to update vscode to v1.21.0 because of the API change.

**Comment by Amomum** [comment]
My bad, I'm too used to vscode suggesting to update every five minutes. Commands work now.
However, when I tried to recreate TOC for my example, it generated exactly the same TOC, git diff showed no changes.

I  added another header to force a change and pushed it; unfortunately, links with cyrillic symbols still do not work in firefox or chrome:
https://github.com/Amomum/test_TOC

**Comment by neilsustc** [comment]
I guess you forgot the newly introduced setting `encodeUrl`. You need to change it to `false` then your text won't be encoded 😉

**Comment by Amomum** [comment]
Oh my god, I'm sorry -_-'

However, I changed encodeUri (i guess you meant encodeUri, not encodeUrl?), TOC changed - there is no more percent encoding in cyrillic links.
But they still don't work. What am I missing now? :)

**Comment by neilsustc** [comment]
That's strange. Have you pushed your change to GitHub?
It works if I manually edit the HTML code on <https://github.com/Amomum/test_TOC>
(e.g. `<a href="#%...%..." ...>...</a>` -> `<a href="#Ляляля" ...>...</a>`)

**Comment by Amomum** [comment]
I did the push, raw file shows no percent-encoding - https://raw.githubusercontent.com/Amomum/test_TOC/master/README.md

**Comment by Amomum** [comment]
I thought maybe github was playing some caching games and did a push to another repo - results are the same: https://github.com/Amomum/test_TOC2

**Comment by neilsustc** [comment]
Oh, it seems that you find a GitHub bug!
Open `https://github.com/Amomum/test_TOC/blob/master/README.md#Ляляля` -> works well (jumps to the right place)
Then the url is auto changed to `https://github.com/Amomum/test_TOC/blob/master/README.md#%D0%9B%D1%8F%D0%BB%D1%8F%D0%BB%D1%8F` by Chrome. -> still works well
The problem is that the link in TOC (which is encoded by GitHub) is `https://github.com/Amomum/test_TOC/blob/master/README.md#%D0%BB%D1%8F%D0%BB%D1%8F%D0%BB%D1%8F` -> of course it doesn't work

Now the "spot the difference" game
`#%D0%9B%D1%8F%D0%BB%D1%8F%D0%BB%D1%8F`
`#%D0%BB%D1%8F%D0%BB%D1%8F%D0%BB%D1%8F`
Do you see? 😂

**Comment by Amomum** [comment]
Oh dear :) Uppercase letter `Л` changed to lowercase `л`. Hmm. I guess I will report this to github then :)
Thanks for  help!

**Comment by neilsustc** [comment]
Good luck
