### ISSUE TITLE
Default keybinding of `toggleStrikethrough`

### ISSUE THREAD

**Issue by maranomynet** [neilsustc/vscode-markdown#91]
This would make managing ToDo lists so much nicer.

Also, a keyboard shortcut for strikethrough would be nice.

```
{
    "key": "alt+s",
    "command": "markdown.extension.editing.toggleStrikethrough",
    "when": "editorTextFocus && editorLangId == 'markdown'"
}
```

**Comment by neilsustc** [comment]
You can custom your keybindings like [this](https://github.com/neilsustc/vscode-markdown/issues/88#issuecomment-364628067).

BTW, you might also like to try [todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus).

**Comment by maranomynet** [comment]
The shortcut code above is pasted out of my own custom keybindings.json file.
It would just be nice to have it bound by default.

Also the main point is for the extension to highlighting/gray-out text with `~`s around it.

**Comment by maranomynet** [comment]
I didn't realise the syntax highlight was VSCode's responsibility. I'll take it up with them. Thanks!

**Comment by neilsustc** [comment]
The reason I didn't assign a default shortcut for `toggleStrikethrough` is because I didn't find a good one.
I will leave this open to see other users' opinions.

**Comment by maranomynet** [comment]
`Alt+s` has been working nicely for me and fits nicely with `Cmd+c` for toggling task items.

**Comment by godaygo** [comment]
Since this is in principle related, I wrote here instead of opening a new issue.

Will you consider to implement the similar functionality for ToDo list like this?
https://github.com/PKief/vscode-markdown-checkbox
Also I found "Information in status bar" is rather useful for Projects ToDo. 

I understand that this functionality is far from Markdown, but maybe it correlates with your idea what is or does not resemble your project.

**Comment by maranomynet** [comment]
Also, IMO, the `toggleStrikethrough` command should act on the current line/paragraph as a whole, if no text is selected.

**Comment by neilsustc** [comment]
@godaygo I think the current solution (automatically add `- [ ]` when you press <kbd>Enter</kbd>) is better because you don't need to press other keybindings to "create task list".
As for the statusbar information of to-do, I am afraid it is not in my plan because personally I prefer to use other extension (like todo+ mentioned above).

@maranomynet It sounds like "quick mode" (like toggling bold). One difference is that "quick mode" of this extension smartly select the **word** under your cursor rather than a whole line/paragraph.

**Comment by maranomynet** [comment]
Awkward. I just found out about quick mode. I like it, and appreciate the idea of making strikethrough behavie consistently with bold and italic.

However, my personal usage of strikethrough is like 95% to strike out whole lines in a bullet list of todos (or task items)

**Comment by neilsustc** [comment]
I just checked my code and the most easy way is reusing the "quick mode" code. That says that strikethrough will behave the same way as bold/italic.
I guess that striking out a task list is not a frequently used command. So let's live with its absence 😅

**Comment by neilsustc** [comment]
Oh, I didn't realize that I already implemented it 😂

**Comment by maranomynet** [comment]
An option to strike the whole line would be sweet though ;-)

**Comment by neilsustc** [comment]
I'll do it after the Spring Festival

**Comment by neilsustc** [comment]
Although it is not documented, I can tell you secretly that quick mode will strike-through the whole line in task list (in v1.1.0) 😎

**Comment by neilsustc** [comment]
I change my mind now. Let's assign `alt+s` as the default keybinding.

As for this ~~strikethrough~~ decoration, I recommend [Highlight](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight) extension with this setting

```
"highlight.regexes": {
    "(~~.+?~~)": [
        {
            "rangeBehavior": 1,
            "textDecoration": "line-through"
        }
    ]
},
```
